import type { ManifestEntry } from '../knowledge/types.js';

/**
 * Sitemap parsing. Main thread, because it uses `DOMParser` — worth it for a
 * native, entity- and CDATA-correct XML parse rather than a regex that works
 * until it meets a sitemap generated by something unusual.
 */

export interface SitemapResult {
  urls: ManifestEntry[];
  /** Nested sitemap URLs, when the document is a <sitemapindex>. */
  sitemaps: string[];
}

export function parseSitemap(xml: string, baseUrl: string): SitemapResult {
  const doc = new DOMParser().parseFromString(xml, 'application/xml');
  if (doc.getElementsByTagName('parsererror').length > 0) {
    throw new Error('sitemap is not well-formed XML');
  }

  // Match on local name so any namespace prefix works.
  const nested = [...doc.getElementsByTagNameNS('*', 'sitemap')]
    .map((el) => text(el, 'loc'))
    .filter((loc): loc is string => Boolean(loc))
    .map((loc) => absolute(loc, baseUrl))
    .filter((loc): loc is string => Boolean(loc));

  const urls: ManifestEntry[] = [];
  const seen = new Set<string>();

  for (const el of doc.getElementsByTagNameNS('*', 'url')) {
    const loc = text(el, 'loc');
    if (!loc) continue;
    const url = absolute(loc, baseUrl);
    if (!url || seen.has(url)) continue;
    seen.add(url);

    urls.push({
      url,
      ...describeUrl(url),
      lastmod: text(el, 'lastmod'),
      priority: numeric(text(el, 'priority')),
    });
  }

  return { urls, sitemaps: nested };
}

/**
 * What we can know about a page without fetching it: a readable title from the
 * slug, and the path segments that become the category tree. This is the whole
 * routing manifest for a lazily-crawled site — cheap enough to build for every
 * URL in a sitemap, and good enough to decide which pages are worth fetching.
 */
export function describeUrl(url: string): { slugTitle: string; segments: string[] } {
  let path: string;
  try {
    path = new URL(url).pathname;
  } catch {
    path = url;
  }

  const parts = path.split('/').filter((p) => p.length > 0);
  const last = parts[parts.length - 1] ?? '';
  const stem = last.replace(/\.[a-z0-9]+$/i, '');

  // `/docs/index.html` is really "Docs", not "Index".
  const isIndex = stem === '' || stem.toLowerCase() === 'index';
  const titleSource = isIndex ? (parts[parts.length - 2] ?? 'Home') : stem;
  const segments = isIndex ? parts.slice(0, -1) : parts.slice(0, -1);

  return { slugTitle: humanize(titleSource), segments };
}

function humanize(slug: string): string {
  const words = slug
    .replace(/\.[a-z0-9]+$/i, '')
    .split(/[-_\s]+/)
    .filter((w) => w.length > 0);
  if (words.length === 0) return 'Home';
  return words.map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

function text(parent: Element, localName: string): string | null {
  for (const child of parent.children) {
    if (child.localName === localName) return child.textContent?.trim() || null;
  }
  return null;
}

function numeric(value: string | null): number | null {
  if (value === null) return null;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : null;
}

function absolute(url: string, base: string): string | null {
  try {
    const resolved = new URL(url, base);
    return resolved.protocol === 'http:' || resolved.protocol === 'https:' ? resolved.href : null;
  } catch {
    return null;
  }
}
