import { describeUrl } from '../knowledge/urls.js';
import type { ManifestEntry } from '../knowledge/types.js';

/**
 * Sitemap parsing. Main thread, because it uses `DOMParser` — worth it for a
 * native, entity- and CDATA-correct XML parse rather than a regex that works
 * until it meets a sitemap generated by something unusual.
 */

export { describeUrl } from '../knowledge/urls.js';

export interface SitemapResult {
  urls: ManifestEntry[];
  /** Nested sitemap URLs, when the document is a <sitemapindex>. */
  sitemaps: string[];
}

export function parseSitemap(xml: string, baseUrl: string): SitemapResult {
  const doc = new DOMParser().parseFromString(xml, 'application/xml');
  if (doc.getElementsByTagName('parsererror').length > 0) {
    throw new Error('sitemap is not well-formed XML');
  }

  // Match on local name so any namespace prefix works.
  const nested = [...doc.getElementsByTagNameNS('*', 'sitemap')]
    .map((el) => text(el, 'loc'))
    .filter((loc): loc is string => Boolean(loc))
    .map((loc) => absolute(loc, baseUrl))
    .filter((loc): loc is string => Boolean(loc));

  const urls: ManifestEntry[] = [];
  const seen = new Set<string>();

  for (const el of doc.getElementsByTagNameNS('*', 'url')) {
    const loc = text(el, 'loc');
    if (!loc) continue;
    const url = absolute(loc, baseUrl);
    if (!url || seen.has(url)) continue;
    seen.add(url);

    urls.push({
      url,
      ...describeUrl(url),
      lastmod: text(el, 'lastmod'),
      priority: numeric(text(el, 'priority')),
    });
  }

  return { urls, sitemaps: nested };
}

function text(parent: Element, localName: string): string | null {
  for (const child of parent.children) {
    if (child.localName === localName) return child.textContent?.trim() || null;
  }
  return null;
}

function numeric(value: string | null): number | null {
  if (value === null) return null;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : null;
}

function absolute(url: string, base: string): string | null {
  try {
    const resolved = new URL(url, base);
    return resolved.protocol === 'http:' || resolved.protocol === 'https:' ? resolved.href : null;
  } catch {
    return null;
  }
}
